### ISSUE TITLE
Heading is not readable in Contributor Section

### ISSUE THREAD

**Issue by mayank2002-jpg** [dikshantrajput/hacktoberfest-2022-react#16]
![Screenshot (17)](https://user-images.githubusercontent.com/74871225/193443487-95d92f1a-4758-4541-ae18-b7ef36ca7b0b.png)
Kindly assign this issue to me!

**Comment by dikshantrajput** [comment]
Ya sure go ahead. Assigned to you. Thanks for pointing out. Also fix the un necessary margins and padding on buttons if you can.

**Comment by mayank2002-jpg** [comment]
Ok sure!
