### ISSUE TITLE
No "Load More" for contributors less than limit per page

### ISSUE THREAD

**Issue by sureemo** [dikshantrajput/hacktoberfest-2022-react#19]
If the data is less than `10` (limit per page), should not display `Load More` button.

<img width="880" alt="Screen Shot 2565-10-02 at 15 07 10" src="https://user-images.githubusercontent.com/1849256/193444481-7580f70b-e5c5-4b6d-b2e1-23b6ce7c49f5.png">

**Comment by maheshjainckd** [comment]
@sureemo do you want to work on this?

**Comment by anudeeps0306** [comment]
can you assign this to me?

**Comment by maheshjainckd** [comment]
> can you assign this to me?

Assigned it to you. Go ahead ;)
