### ISSUE TITLE
Improve responsive view

### ISSUE THREAD

**Issue by sureemo** [dikshantrajput/hacktoberfest-2022-react#26]
Improve interface for mobile view e.g. nav bar

<img width="291" alt="Screen Shot 2565-10-02 at 19 01 54" src="https://user-images.githubusercontent.com/1849256/193452965-1805a1ca-b877-4f5f-b7a1-4f306b91b8e1.png">

**Comment by sureemo** [comment]
If approved, kindly assign to me. Thank you ^_^

**Comment by RahulRudra81** [comment]
i can create a drop down of nav bar in mobile view. Can I work on it too??

**Comment by maheshjainckd** [comment]
> i can create a drop down of nav bar in mobile view. Can I work on it too??

Yeah sure.
