### ISSUE TITLE
Have problem with the project setup

### ISSUE THREAD

**Issue by kkartik07** [dikshantrajput/hacktoberfest-2022-react#59]
Hello everyone!
This is first time me contributing to a React project. I am nit able to see changes that I make in the website running on localhost.
For project setup I followed the following steps:
    1. npm install
    2. npm start
  
Please help me so that I can get started. Thanks.

**Comment by issa-hassane** [comment]
Hello....
run this command first:
npm install -g npm@8.19.2

then precede with the usual steps

**Comment by kkartik07** [comment]
Thanks..it worked😃
