### ISSUE TITLE
Fixing footer to the bottom of the page in light mode.

### ISSUE THREAD

**Issue by Rohit-Saini7** [dikshantrajput/hacktoberfest-2022-react#68]
Everything is right in dark mode.

![1](https://user-images.githubusercontent.com/95734284/195007809-f8673f3e-b42c-4145-8fb4-a25a4830f595.png)

But,
when someone switches to light mode footer changes its position and comes up from its original position.
![2](https://user-images.githubusercontent.com/95734284/195007838-0867d20f-bb10-4614-ae6d-c626630b3b8f.png)

**Comment by Rohit-Saini7** [comment]
I have fixed it (#69), so please merge it.

**Comment by aakanksha1801** [comment]
can i do it ?
