### ISSUE TITLE
Fix buttons, box-shadow and make dark mode default

### ISSUE THREAD

**Issue by dikshantrajput** [dikshantrajput/hacktoberfest-2022-react#9]
Any one wants to pick the issue up. I will assign to him/her

**Comment by mayank2002-jpg** [comment]
I want to work on this issue. Kindly assign me.

**Comment by dikshantrajput** [comment]
Here you go

**Comment by AyushBorage28** [comment]
I am an experienced web developer. You can assign this issue to me

**Comment by dikshantrajput** [comment]
@AyushBorage28 You can work on making dark mode default and @mayank2002-jpg you can work on rest of things. Thanks

**Comment by mayank2002-jpg** [comment]
ok sure. Thanks for assigning me!

**Comment by AyushBorage28** [comment]
> @AyushBorage28 You can work on making dark mode default and @mayank2002-jpg you can work on rest of things. Thanks

No problem

**Comment by AyushBorage28** [comment]
Hey @dikshantrajput ,
Have Successfuly Made the Dark Mode as Default.
Thank You for assigning the task  to me.

**Comment by mayank2002-jpg** [comment]
Sir, I have an issue regarding hacktoberfest. As I make 2 pr in your repo but on hacktoberfest website, it is showing excluded. Kindly solve this issue
![Screenshot (18)](https://user-images.githubusercontent.com/74871225/193459337-1b333fcf-d27b-41d9-aa2b-6a03724c9d57.png)

**Comment by maheshjainckd** [comment]
> Sir, I have an issue regarding hacktoberfest. As I make 2 pr in your repo but on hacktoberfest website, it is showing excluded. Kindly solve this issue ![Screenshot (18)](https://user-images.githubusercontent.com/74871225/193459337-1b333fcf-d27b-41d9-aa2b-6a03724c9d57.png)

Sorry to inform, but this repo is excluded from hacktoberfest2022. We don't know exactly why it got excluded. Still You can contribute to any other open source projects for Hacktoberfest. Thanks
